// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY_gde-4Pm9f73gyRYsx-gp-TRieDT9M8',
    appId: '1:498124910842:web:cf4bd6cc7b35573a41d943',
    messagingSenderId: '498124910842',
    projectId: 'jewellery-nafisa',
    authDomain: 'jewellery-nafisa.firebaseapp.com',
    storageBucket: 'jewellery-nafisa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCycwT96bAxii5poriygbQA79L6ZSJKKCE',
    appId: '1:498124910842:android:41d2e6870adb1dd941d943',
    messagingSenderId: '498124910842',
    projectId: 'jewellery-nafisa',
    storageBucket: 'jewellery-nafisa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0B7_UGp4wFfjOZ6ZYNTChj187LmXAJfo',
    appId: '1:498124910842:ios:63b7695091b08d1e41d943',
    messagingSenderId: '498124910842',
    projectId: 'jewellery-nafisa',
    storageBucket: 'jewellery-nafisa.firebasestorage.app',
    iosClientId:
        '498124910842-nlc18c7irm4vlbnkvjlr7hg3nclrkue1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewelryNafisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0B7_UGp4wFfjOZ6ZYNTChj187LmXAJfo',
    appId: '1:498124910842:ios:63b7695091b08d1e41d943',
    messagingSenderId: '498124910842',
    projectId: 'jewellery-nafisa',
    storageBucket: 'jewellery-nafisa.firebasestorage.app',
    iosClientId:
        '498124910842-nlc18c7irm4vlbnkvjlr7hg3nclrkue1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewelryNafisa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY_gde-4Pm9f73gyRYsx-gp-TRieDT9M8',
    appId: '1:498124910842:web:513d3d6aef18bd0941d943',
    messagingSenderId: '498124910842',
    projectId: 'jewellery-nafisa',
    authDomain: 'jewellery-nafisa.firebaseapp.com',
    storageBucket: 'jewellery-nafisa.firebasestorage.app',
  );
}
