// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQwJ_i-1CL8284G5mPmTA8Uh9J85u-uGk',
    appId: '1:367777430992:web:f55f86ab9a33b36d468dd5',
    messagingSenderId: '367777430992',
    projectId: 'dagina-designs',
    authDomain: 'dagina-designs.firebaseapp.com',
    storageBucket: 'dagina-designs.firebasestorage.app',
    measurementId: 'G-8LK7Z330ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Pv0rmEInD1oUve9DbtxxKRSHOgad7Tc',
    appId: '1:367777430992:android:9bf2d82479435539468dd5',
    messagingSenderId: '367777430992',
    projectId: 'dagina-designs',
    storageBucket: 'dagina-designs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKP2lWnopUn3g0D9T_L48Wzf-0iPSpeIs',
    appId: '1:367777430992:ios:9969ce824bea59d7468dd5',
    messagingSenderId: '367777430992',
    projectId: 'dagina-designs',
    storageBucket: 'dagina-designs.firebasestorage.app',
    iosBundleId: 'com.example.jewelryNafisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKP2lWnopUn3g0D9T_L48Wzf-0iPSpeIs',
    appId: '1:367777430992:ios:9969ce824bea59d7468dd5',
    messagingSenderId: '367777430992',
    projectId: 'dagina-designs',
    storageBucket: 'dagina-designs.firebasestorage.app',
    iosBundleId: 'com.example.jewelryNafisa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQwJ_i-1CL8284G5mPmTA8Uh9J85u-uGk',
    appId: '1:367777430992:web:faacb2fa88371dac468dd5',
    messagingSenderId: '367777430992',
    projectId: 'dagina-designs',
    authDomain: 'dagina-designs.firebaseapp.com',
    storageBucket: 'dagina-designs.firebasestorage.app',
    measurementId: 'G-X6JQX6NZMY',
  );

}