
ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS is_member BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS last_credit_refresh TIMESTAMPTZ;

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS membership_plan TEXT;

ALTER TABLE public.users
DROP COLUMN IF EXISTS membership_status;